notifications:
  email: false

sudo: required

services:
  - docker

script:
  - docker-compose build
  # - docker-compose run charity /bin/sh -c "npm run lint && npm test"
  - docker-compose run charity /bin/sh -c "npm run lint"

# after_success:
  # - docker-compose run charity /bin/sh -c "COVERALLS_SERVICE_NAME=${COVERALLS_SERVICE_NAME} COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} npm run coveralls"

after_script:
  - docker-compose down
