version: "3"

volumes:
  database:
  search:

services:

  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      # Expose port to host machine for debugging
      - 27017
    volumes:
      - database:/data/db

  search:
    container_name: search
    image: blacktop/elasticsearch:6.1
    ports:
      # Expose port to host machine for debugging
      - 9200:9200
    volumes:
      - search:/data

  charity:
    container_name: charity
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        APP_URL: ${APP_URL}
    environment:
      - NODE_ENV
      - NODE_CONFIG_DIR
      - APP_URL
      - APP_PORT
      - TOKEN_SECRET
      - SYSTEM_USERS_GUEST_ID
      - SYSTEM_USERS_GUEST_EMAIL
    volumes:
      # Make the following directories available to docker so that changes made on the host
      # are immediately available inside the docker container.
      - ./package.json:/app/package.json
      - ./gulpfile.js:/app/gulpfile.js
      - ./docker-compose.sh:/app/docker-compose.sh
      - ./src:/app/src
    command: ./docker-compose.sh #npm start
    ports:
      # Expose port to host machine for debugging
      - 80:80
    links:
      - mongo
      - search
